import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { expenseAPI, budgetAPI, analyticsAPI } from '../services/api';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import PageLoader from '../components/PageLoader';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function PDFReport() {
    const { user } = useAuth();
    const [loading, setLoading] = useState(true);
    const [reportData, setReportData] = useState(null);
    const [generating, setGenerating] = useState(false);
    const navigate = useNavigate();

    useEffect(() => {
        fetchReportData();
    }, []);

    const fetchReportData = async () => {
        try {
            const [statsRes, budgetRes, analyticsRes] = await Promise.all([
                expenseAPI.getStats(),
                budgetAPI.getStatus(),
                analyticsAPI.getData()
            ]);

            setReportData({
                stats: statsRes.data.stats,
                budget: budgetRes.data.budget,
                analytics: analyticsRes.data.analytics
            });
        } catch (error) {
            console.error('Error fetching report data:', error);
        } finally {
            setLoading(false);
        }
    };

    const generatePDF = () => {
        setGenerating(true);

        try {
            const doc = new jsPDF();
            const currentDate = new Date();
            const monthYear = currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

            // Header
            doc.setFillColor(139, 92, 246);
            doc.rect(0, 0, 210, 40, 'F');

            doc.setTextColor(255, 255, 255);
            doc.setFontSize(24);
            doc.text('Expense Report', 105, 20, { align: 'center' });

            doc.setFontSize(12);
            doc.text(monthYear, 105, 30, { align: 'center' });

            // User Info
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(10);
            doc.text(`Name: ${user.name}`, 20, 50);
            doc.text(`Email: ${user.email}`, 20, 56);
            doc.text(`Generated: ${currentDate.toLocaleDateString()}`, 20, 62);

            // Summary Section
            doc.setFontSize(16);
            doc.setTextColor(139, 92, 246);
            doc.text('Summary', 20, 75);

            doc.setFontSize(11);
            doc.setTextColor(0, 0, 0);
            doc.text(`Total Spent: ₹${reportData.stats.totalSpent}`, 20, 85);
            doc.text(`Monthly Budget: ₹${reportData.budget.monthlyBudget}`, 20, 92);
            doc.text(`Remaining: ₹${reportData.budget.remaining}`, 20, 99);
            doc.text(`Budget Used: ${reportData.budget.percentageUsed}%`, 20, 106);

            // Category Breakdown Table
            doc.setFontSize(16);
            doc.setTextColor(139, 92, 246);
            doc.text('Category Breakdown', 20, 120);

            const categoryData = Object.entries(reportData.stats.categoryBreakdown).map(([category, amount]) => [
                category,
                `₹${amount}`,
                `${reportData.analytics.categoryPercentages[category]}%`
            ]);

            doc.autoTable({
                startY: 125,
                head: [['Category', 'Amount', 'Percentage']],
                body: categoryData,
                theme: 'grid',
                headStyles: { fillColor: [139, 92, 246] },
                styles: { fontSize: 10 }
            });

            // Insights Section
            const finalY = doc.lastAutoTable.finalY + 15;
            doc.setFontSize(16);
            doc.setTextColor(139, 92, 246);
            doc.text('Insights', 20, finalY);

            doc.setFontSize(10);
            doc.setTextColor(0, 0, 0);
            let insightY = finalY + 8;

            // Add insights
            const insights = [
                `• Highest spending category: ${reportData.analytics.highestCategory}`,
                `• Total expenses tracked: ${reportData.stats.expenseCount}`,
                `• Budget status: ${reportData.budget.warningLevel.toUpperCase()}`,
            ];

            insights.forEach(insight => {
                doc.text(insight, 20, insightY);
                insightY += 7;
            });

            // Footer
            doc.setFontSize(8);
            doc.setTextColor(128, 128, 128);
            doc.text('Generated by Smart Expense Splitter', 105, 285, { align: 'center' });

            // Save PDF
            const fileName = `Expense_Report_${monthYear.replace(' ', '_')}.pdf`;
            doc.save(fileName);

        } catch (error) {
            console.error('Error generating PDF:', error);
        } finally {
            setGenerating(false);
        }
    };

    if (loading) {
        return <PageLoader />;
    }

    return (
        <div className="min-h-screen bg-dark-900 py-8">
            <div className="container mx-auto px-4 max-w-4xl">
                <div className="mb-6">
                    <button
                        onClick={() => navigate('/dashboard')}
                        className="text-gray-400 hover:text-white transition-colors"
                    >
                        ← Back to Dashboard
                    </button>
                </div>

                <h1 className="text-4xl font-bold mb-8">
                    <span className="bg-gradient-to-r from-accent-violet to-accent-cyan bg-clip-text text-transparent">
                        Monthly Report
                    </span>
                </h1>

                {/* Preview Card */}
                <Card className="mb-6">
                    <h2 className="text-2xl font-bold mb-6">Report Preview</h2>

                    <div className="space-y-6">
                        {/* Summary */}
                        <div>
                            <h3 className="text-lg font-semibold mb-3 text-accent-violet">Summary</h3>
                            <div className="grid md:grid-cols-2 gap-4">
                                <div className="glass rounded-lg p-4">
                                    <div className="text-sm text-gray-400">Total Spent</div>
                                    <div className="text-2xl font-bold">₹{reportData.stats.totalSpent}</div>
                                </div>
                                <div className="glass rounded-lg p-4">
                                    <div className="text-sm text-gray-400">Monthly Budget</div>
                                    <div className="text-2xl font-bold">₹{reportData.budget.monthlyBudget}</div>
                                </div>
                                <div className="glass rounded-lg p-4">
                                    <div className="text-sm text-gray-400">Remaining</div>
                                    <div className={`text-2xl font-bold ${reportData.budget.remaining < 0 ? 'text-red-400' : 'text-green-400'}`}>
                                        ₹{reportData.budget.remaining}
                                    </div>
                                </div>
                                <div className="glass rounded-lg p-4">
                                    <div className="text-sm text-gray-400">Budget Used</div>
                                    <div className="text-2xl font-bold">{reportData.budget.percentageUsed}%</div>
                                </div>
                            </div>
                        </div>

                        {/* Category Breakdown */}
                        <div>
                            <h3 className="text-lg font-semibold mb-3 text-accent-violet">Category Breakdown</h3>
                            <div className="space-y-2">
                                {Object.entries(reportData.stats.categoryBreakdown).map(([category, amount]) => (
                                    <div key={category} className="glass rounded-lg p-3 flex items-center justify-between">
                                        <span className="font-semibold">{category}</span>
                                        <div className="text-right">
                                            <div className="font-bold">₹{amount}</div>
                                            <div className="text-sm text-gray-400">
                                                {reportData.analytics.categoryPercentages[category]}%
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Insights */}
                        <div>
                            <h3 className="text-lg font-semibold mb-3 text-accent-violet">Insights</h3>
                            <div className="glass rounded-lg p-4 space-y-2">
                                <p>• Highest spending category: <strong>{reportData.analytics.highestCategory}</strong></p>
                                <p>• Total expenses tracked: <strong>{reportData.stats.expenseCount}</strong></p>
                                <p>• Budget status: <strong className="uppercase">{reportData.budget.warningLevel}</strong></p>
                            </div>
                        </div>
                    </div>
                </Card>

                {/* Download Button */}
                <Card variant="gradient" className="text-center">
                    <div className="text-5xl mb-4">📄</div>
                    <h3 className="text-2xl font-bold mb-2">Ready to Download</h3>
                    <p className="opacity-90 mb-6">
                        Your monthly expense report is ready. Click below to download as PDF.
                    </p>
                    <Button
                        onClick={generatePDF}
                        loading={generating}
                        variant="secondary"
                        className="bg-white text-accent-violet hover:bg-gray-100"
                    >
                        {generating ? 'Generating PDF...' : 'Download PDF Report'}
                    </Button>
                </Card>
            </div>
        </div>
    );
}
